USE tarefa_3;

/*LISTANDO AS 10 OPERADORAS QUE TIVERAM A MAIOR DESPESA DURANTE O ÚLTIMO TRIMESTRE*/
SELECT rel.RAZAO_SOCIAL,rel.Registro_ANS,SUM(reg.VL_SALDO_FINAL)
FROM table_5 as reg 
JOIN table_relatorio as rel
ON reg.REG_ANS = rel.Registro_ANS
WHERE reg.VL_SALDO_FINAL < 0
GROUP BY  reg.REG_ANS
ORDER BY SUM(reg.VL_SALDO_FINAL) ASC LIMIT 10;

/*LISTANDO AS 10 OPERADORAS QUE TIVERAM A MAIOR DESPESA DESDE O PRIMEIRO TRIMESTRE DE 2020*/
SELECT rel.RAZAO_SOCIAL,rel.Registro_ANS,SUM(reg.VL_SALDO_FINAL) 
FROM (SELECT REG_ANS,VL_SALDO_FINAL from table_1 UNION ALL
      SELECT REG_ANS,VL_SALDO_FINAL from table_2 UNION ALL
      SELECT REG_ANS,VL_SALDO_FINAL from table_3 UNION ALL
      SELECT REG_ANS,VL_SALDO_FINAL from table_4 UNION ALL
      SELECT REG_ANS,VL_SALDO_FINAL from table_5) as reg
JOIN table_relatorio as rel
ON reg.REG_ANS = rel.Registro_ANS
WHERE reg.VL_SALDO_FINAL < 0
GROUP BY  reg.REG_ANS
ORDER BY SUM(reg.VL_SALDO_FINAL) ASC LIMIT 10;

/*DEIXAREI OS RESULTADOS ENCONTRADOS SALVOS NA PASTA DAS QUERYs*/
